"""add_content_is_user_edited

Revision ID: effcf9c68468
Revises: 20260401_0005
Create Date: 2026-04-06 20:00:06.808239
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effcf9c68468'
down_revision = '20260401_0005'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    return any(column["name"] == column_name for column in sa.inspect(bind).get_columns(table_name))


def _index_exists(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    return any(index["name"] == index_name for index in sa.inspect(bind).get_indexes(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('contents', 'is_user_edited'):
        op.add_column('contents', sa.Column('is_user_edited', sa.Boolean(), nullable=True))
    if not _index_exists('contents', 'ix_content_updated_at'):
        op.create_index('ix_content_updated_at', 'contents', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_updated_at', table_name='contents')
    op.drop_column('contents', 'is_user_edited')
    # ### end Alembic commands ###
