import asyncio
from app.collectors.website import WebsiteCollector

URL = "https://news.google.com/rss/articles/CBMilwNBVV95cUxOMGh6Wm9iOFJtSlNadVFKSmdmc29Ga3pmWHZSZkJJR2FWRWlDckRvcGhsN3FyZ1p5enFMNFhvcXU2dUVfREFHUml3elFlQkd6TksyWDI0a3I0QTY4dVhGZXBVcnNTcEZIbnVlbmJ3ZnVVcUdvU0c1WFlIWEJDYVJvYWVRd1JSZ2lXNGF5dThmbEU1UjlZbjFQNzlZZEdSakdCWVBKZjB0ZUVIN0Q2c1ZHbFFrRjJGSndGWjd6YnVhb2ZIRmZZSUdybklDZGFoR3ZSMWEyS1l4ajRrZmFzU1J2alViUzhzNmh5cEx1LVJBREl0NmpVeWtqZEVlbjlXd0p0Wnktb2MwOW1fT0I4bk1LWk4wN0Utcmp5d0xsbjRXdWtFbkRUelFrZFl0aG00c2N4MGs0TVJfNllST0NTZldqRk1CbWhTSllWX3FNcFdIanZ0aWRjaXctT2lFQkJhU3RjSlp0ZmpGNFVnT0kwdWpGa3NBVC01WEhYSGVQc1ZINS1hSUNZdXAyQTdLNlI5cGNDVk1mQk5RWQ?oc=5"

async def main():
    c=WebsiteCollector()
    print('is_wrapper', c._is_google_news_wrapper(URL))
    resolved=await c._resolve_google_wrapper_url_with_playwright(URL)
    print('resolved=',resolved)

asyncio.run(main())
